### ISSUE TITLE
Cluster Tracking Issue

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#14]
This issue tracks implementation of clustering into Toshi.

- [x] Decide on clustering method (master/client, masterless). Relates to #15 
- [x] Add CLI flag for Consul cluster address. Relates to #18 
- [x] Add CLI flag for cluster name. Relates to #19 
- [x] Decide on shard replication scheme. Relates to #16.
- [ ] Enumerate failure modes
- [ ] Write tests for failure modes (network splits, etc)
- [ ] Write module to register with Consul. Relates to #24.

### * High jacking Fletcher's issue for my own tracking * - Steve
I've laid out some of the groundwork for this with tower-grpc, so I should be able to get rolling with this today. 

Things I'd like to do by end of the year
- [ ] Create master election
  - [ ] A way to just tell Toshi the masters and nodes without consul doing it
  - [x] Have nodes report the indexes they have to consul for Placement Driver
- [x] Extend `IndexHandle` to understand it might have to do an rpc call to fullfill a query
- [x] Move current `IndexHandle` into `LocalIndexHandle`
- [x] Move Index Searching into `IndexHandle` and out of `IndexCatalog`
- [x] Extend `IndexCatalog` to include both `LocalIndexHandle` and `RemoteIndexHandle`
- [ ] Attempt to re-factor / re-use as much of the searching / indexing code available to fullfill RPC needs
- [x] Get a working, naive base case working for distributed, index creation, document addition and searching.
- [ ] Finish the 3000 commendation score Shield in The Division

**Comment by fhaynes** [comment]
```
                                                   .───────.                                                   
                                                  ( Client  )                                                  
                                                   `───────'                                                   
                                                       │                                                       
                                                       │                                                       
                                                       │                                                       
                                                       │                                                       
                                                       │                                                       
                                              ┌────────┼────────┐                                              
                                              │        │        │                                              
                                              │        │        │                                              
                                              │        │        │                                              
                                              │        │        │                                              
                                              │        ▼        │                                              
                                              │  ┌───────────┐  │                                              
┌─────────────────────────────────────────────┴─▶┤  Index 1  ├◀─┴─────────────────────────────────────────────┐
│                                                └───────────┘                                                │
│                                                      │                                                      │
│                            ┌─────────────────────────┼───────────────────────────┐                          │
│                            ▼                         │                           ▼                          │
│                       ┌─────────┐                    │                      ┌─────────┐                     │
│                       │ Primary │                    │                      │ Primary │                     │
│          ┌────────────│ Shard 1 │────────────┐       │         ┌────────────│ Shard 2 │────────────┐        │
│          │            └─────────┘            │       │         │            └─────────┘            │        │
│          │                 │                 │       │         │                 │                 │        │
│          │                 │                 │       │         │                 │                 │        │
│          │                 │                 │       │         │                 │                 │        │
│          ▼                 ▼                 ▼       │         ▼                 ▼                 ▼        │
│    ┌───────────┐     ┌───────────┐     ┌───────────┐ │   ┌───────────┐     ┌───────────┐     ┌───────────┐  │
│    │  Replica  │     │  Replica  │     │  Replica  │ │   │  Replica  │     │  Replica  │     │  Replica  │  │
│    │  Shard 1  │     │  Shard 2  │     │  Shard 3  │ │   │  Shard 1  │     │  Shard 2  │     │  Shard 3  │  │
│    └───────────┘     └───────────┘     └───────────┘ │   └───────────┘     └───────────┘     └───────────┘  │
│                                                      │                                                      │
│                                                      │                                                      │
│                                                      │                                                      │
│                                                      │                                                      │
│                                                      ▼                                                      │
│                                                 ┌─────────┐                                                 │
│                                                 │ Primary │                                                 │
│                                    ┌────────────│ Shard 2 │────────────┐                                    │
│                                    │            └─────────┘            │                                    │
│                                    │                 │                 │                                    │
│                                    │                 │                 │                                    │
│                                    │                 │                 │                                    │
│                                    ▼                 ▼                 ▼                                    │
│                              ┌───────────┐     ┌───────────┐     ┌───────────┐                              │
│                              │  Replica  │     │  Replica  │     │  Replica  │                              │
│                              │  Shard 1  │     │  Shard 2  │     │  Shard 3  │                              │
│                              └───────────┘     └───────────┘     └───────────┘                              │
│                                                                                                             │
│                                                                                                             │
│                                                                                                             │
│                                                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by fhaynes** [comment]
@LucioFranco @hntd187 Above is a diagram of how this might work. It is basically how ES works:

1. A Index is composed of Primary Shards, which are writable
2. A Primary Shard can have N replica shards. When a write comes into a Primary Shard, it replicates it to all of its Replica shards
3. In the event of a Primary shard failing, a Replica is promoted to Primary.
4. Replicas can serve read requests
5. A Primary Shard can serve reads or writes
6. Queries are routed by dedicated servers that know where all Shards live

Will write more later

**Comment by fhaynes** [comment]
![toshidiskoverview](https://user-images.githubusercontent.com/4388373/47662774-d4e23680-db58-11e8-8df9-c90b8d74c197.png)

**Comment by fhaynes** [comment]
Above is a simple 3 node Toshi cluster connected to a Consul cluster (which would be 1, 3, or 5 nodes).

Another important thing to note is that the OS will handle a lot of read caching for us, so that doesn't need to be built-in to Toshi.

**Comment by fhaynes** [comment]
A placement algorithm will need to be designed. General constraints are:

1. The Primary shards for an index should live on as many different servers as possible. i.e., if an index has 3 Primary shards, and we have a 3 node cluster, each Toshi node should have 1 Primary shard.

2. Replicas should not live on the same node as a Primary or another Replica if possible

3. In the above example, if each Primary had 3 Replicas, we couldn't avoid putting one Replica on the same server as the Primary. In this case, they should go on different storage devices, assuming the device has registered more than one.

4. Since we are using Consul, we should avoid intra-cluster heartbeats, and instead send heartbeats to Consul. The Leader or metadata process can put a Watch (Consul term) on the status attribute of each node, and handle the event of a failed heartbeat.

**Comment by fhaynes** [comment]
A constraint of ES is that you pick the number of Primary shards at index creation (I believe the default is 3 or 5), and after that, you cannot change the number of Primary shards, except by making a new index with a different number of Primaries. From the ES manual:
```
Splitting a shard is almost equivalent to reindexing your data. It’s a much heavier process than just copying a shard from one node to another.

Splitting is exponential. You start with one shard, then split into two, and then four, eight, sixteen, and so on. Splitting doesn’t allow you to increase capacity by just 50%.

Shard splitting requires you to have enough capacity to hold a second copy of your index. Usually, by the time you realize that you need to scale out, you don’t have enough free space left to perform the split.
```

**Comment by hntd187** [comment]
Of course ES has 900 options, which again, Im not sure if that's a good or bad thing. Either way, everything you wrote sounds good to me, I think whenever we can leverage rust's "closer to metal" nature for performance will be a good thing. It'll make beating ES in these things pretty easy just due to the language itself.

Another thing that jumped out to me here, is how are we going to test all of this? I suppose the placement algorithm and the storage tools can be tested in isolation, but I suppose we're gonna need to either facade or find some way to mock around consul to test the coordination of things.

**Comment by fhaynes** [comment]
> but I suppose we're gonna need to either facade or find some way to mock around consul to test the coordination of things.
Locally, docker-compose. For a full test, usually done before a release, you usually spin up an actual cluster in GCP, AWS, DO, wherever, run a gauntlet of tests, then destroy the resources. That has a monetary cost though.

**Comment by hntd187** [comment]
Depending on how much that shakes out to be I'd be fine with that cost. Who knows maybe somewhere down the line someone will be nice enough to donate cloud time to us, or I could use all the hardware I have laying around to coordinate a weird Frankenstein test suite.
