### ISSUE TITLE
Query Implementation Tracking Issue

### ISSUE THREAD

**Issue by fhaynes** [toshi-search/Toshi#39]
This issue tracks the implementation of the various query types. The ones Tantivvy natively supports are highest priority for implementation, followed by the ones it does not directly support.

## Primary Query Types

- [x] Implement Boolean Query #40 
- [x] Implement Phrase Query #41
- [x] Implement Term Query #42
- [x] Implement Range Query #43
- [x] Implement Regex Query #44
- [x] Implement Fuzzy Query #45

**Comment by hntd187** [comment]
@fhaynes do you wanna merge what is in there now or do you wanna wait until tantivy drops their PR on the collector refactor? We're going to have to adopt it anyways since it's gonna make aggregates significantly easier to implement.
